apiVersion: v1
name: cert-manager
# The version and appVersion fields are set automatically by the release tool
version: v0.1.0
appVersion: v0.1.0
kubeVersion: ">= 1.22.0-0"
description: A Helm chart for cert-manager
